SELECT 
R.FOOD_TYPE,
R.REST_ID,
R.REST_NAME,
R.FAVORITES
FROM REST_INFO AS R
JOIN (
    SELECT
    FOOD_TYPE,
    MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS S
ON R.FAVORITES = S.MAX_FAVORITES
AND R.FOOD_TYPE = S.FOOD_TYPE
ORDER BY R.FOOD_TYPE DESC