-- 코드를 입력하세요
SELECT
    CATEGORY,
    SUM(S.SALES) AS TOTAL_SALES
FROM BOOK AS B
INNER JOIN BOOK_SALES AS S
ON B.BOOK_ID = S.BOOK_ID
AND S.SALES_DATE >= '2022-01-01' 
AND S.SALES_DATE < '2022-02-01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC