SELECT
    BOOK_ID
     , AUTHOR_NAME
     , PUBLISHED_DATE
FROM BOOK
         INNER JOIN AUTHOR
                    ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE CATEGORY = '경제'
ORDER BY PUBLISHED_DATE ASC 