-- https://school.programmers.co.kr/learn/courses/30/lessons/273711

SELECT 
I_2.ITEM_ID,
I_2.ITEM_NAME,
I_2.RARITY
FROM ITEM_INFO AS I_1
INNER JOIN ITEM_TREE AS T
ON I_1.ITEM_ID = T.PARENT_ITEM_ID
INNER JOIN ITEM_INFO AS I_2
ON I_2.ITEM_ID = T.ITEM_ID
WHERE I_1.RARITY = 'RARE'
ORDER BY I_2.ITEM_ID DESC
